controller_list:
  - name: fake_mobile_controller
    joints:
      - wheel_left_joint
      - wheel_right_joint
  - name: fake_arm_controller
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
      - arm_7_joint
      - arm_8_joint
  - name: fake_body_controller
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
      - arm_7_joint
      - arm_8_joint
      - wheel_left_joint
      - wheel_right_joint